app:
  name: "Starter application ipmen.io"

jwt:
  header: Authorization
  expires_in: 30000000 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: caYvPwrb1hFbIc4u5XpGi9HrNe9pt3Jy8SZhnNizOBJSyMbPzEuYxn5cS6L7

server.port: 9999

spring.datasource:
  url: "jdbc:mysql://localhost/starter_application?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8"
  driverClassName: com.mysql.cj.jdbc.Driver
  username: null
  password: "null"
  sql-script-encoding: UTF-8
spring.jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: true
spring.http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true
debug: true

# Multipart
spring.servlet.multipart:
  max-file-size: 3MB
  max-request-size: 4MB
